version: '3.8'

services:
  subject-manager:
    build: .
    ports:
      - "4000:4000"
    volumes:
      # Mount source code for live reloading
      - .:/app
      # Mount database file to persist data
      - ./subject_manager_dev.db:/app/subject_manager_dev.db
      # Mount node_modules to avoid conflicts
      - /app/node_modules
      - /app/deps
      - /app/_build
    environment:
      - MIX_ENV=docker
      - PHX_HOST=localhost
    command: >
      sh -c "
        mix deps.get &&
        mix ecto.setup &&
        mix phx.server
      "
    stdin_open: true
    tty: true
    networks:
      - subject-manager-network

networks:
  subject-manager-network:
    driver: bridge
